/**
 * Catalogue pépinière — données mock (Option C).
 * Structure = modèle de la future table Supabase `catalogue_plants`.
 */

export const CATALOGUE_FAMILLES = [
  "arbustes",
  "vivaces",
  "coniferes",
  "arbres",
  "fleurs",
  "rosiers",
];

export const CATALOGUE_ENVIE_TAGS = [
  "ombre",
  "floraison_violette",
  "persistant",
  "sans_entretien",
  "brise_vue",
];

/** Préfixe client_id analyses — distinct des scans Mes scans. */
export function catalogueClientId(plantId) {
  return `catalogue:${plantId}`;
}

/** Payload JSON stocké dans analyses.result pour une plante catalogue. */
export function plantToAnalysisResult(plant) {
  return {
    id: catalogueClientId(plant.id),
    catalogue_plant_id: plant.id,
    source: "catalogue",
    nom: plant.nom,
    nom_latin: plant.nom_latin || "",
    type: plant.type || "plante",
    famille: plant.famille,
    exposition: plant.exposition,
    taille_adulte: plant.taille_adulte,
    floraison: plant.floraison,
    rusticite: plant.rusticite,
    sol: plant.sol,
    tags_envie: plant.tags_envie || [],
    resume: plant.resume,
  };
}

export const CATALOGUE_PLANTS = [
  {
    id: "hortensia-macrophylla",
    nom: "Hortensia",
    nom_latin: "Hydrangea macrophylla",
    famille: "arbustes",
    type: "plante",
    palette_type: null,
    photo_url: null,
    exposition: "mi-ombre",
    taille_adulte: "1,2 m",
    floraison: "Été · bleu, rose ou blanc",
    rusticite: "Zone 6-9",
    sol: "Terre fraîche, humifère",
    tags_envie: ["ombre"],
    resume: "Mi-ombre · floraison longue",
    populaire: true,
    ordre: 1,
    actif: true,
    source: "catalogue",
  },
  {
    id: "photinia-red-robin",
    nom: "Photinia Red Robin",
    nom_latin: "Photinia × fraseri",
    famille: "arbustes",
    type: "plante",
    palette_type: null,
    photo_url: null,
    exposition: "soleil",
    taille_adulte: "3 m",
    floraison: "Printemps · blanc",
    rusticite: "Zone 7-9",
    sol: "Tout sol drainant",
    tags_envie: ["persistant", "brise_vue"],
    resume: "Soleil · persistant · brise-vue",
    populaire: true,
    ordre: 2,
    actif: true,
    source: "catalogue",
  },
  {
    id: "gaura-lindheimeri",
    nom: "Gaura",
    nom_latin: "Oenothera lindheimeri",
    famille: "vivaces",
    type: "fleur",
    palette_type: null,
    photo_url: null,
    exposition: "soleil",
    taille_adulte: "80 cm",
    floraison: "Été · blanc ou rose",
    rusticite: "Zone 5-9",
    sol: "Sol sec, drainant",
    tags_envie: ["sans_entretien"],
    resume: "Soleil · léger · sans entretien",
    populaire: true,
    ordre: 3,
    actif: true,
    source: "catalogue",
  },
  {
    id: "lavande-officinale",
    nom: "Lavande",
    nom_latin: "Lavandula angustifolia",
    famille: "vivaces",
    type: "fleur",
    palette_type: null,
    photo_url: null,
    exposition: "soleil",
    taille_adulte: "60 cm",
    floraison: "Été · violet",
    rusticite: "Zone 5-8",
    sol: "Sol calcaire, drainant",
    tags_envie: ["sans_entretien", "floraison_violette"],
    resume: "Soleil · parfumée · sec",
    populaire: false,
    ordre: 4,
    actif: true,
    source: "catalogue",
  },
  {
    id: "hosta",
    nom: "Hosta",
    nom_latin: "Hosta sieboldiana",
    famille: "vivaces",
    type: "plante",
    palette_type: null,
    photo_url: null,
    exposition: "ombre",
    taille_adulte: "50 cm",
    floraison: "Été · mauve",
    rusticite: "Zone 4-8",
    sol: "Terre humifère, fraîche",
    tags_envie: ["ombre", "persistant"],
    resume: "Ombre · feuillage décoratif",
    populaire: false,
    ordre: 5,
    actif: true,
    source: "catalogue",
  },
  {
    id: "cedre-liban",
    nom: "Cèdre du Liban",
    nom_latin: "Cedrus libani",
    famille: "coniferes",
    type: "arbre",
    palette_type: "sujet",
    photo_url: null,
    exposition: "soleil",
    taille_adulte: "15 m",
    floraison: null,
    rusticite: "Zone 6-9",
    sol: "Tout sol profond",
    tags_envie: ["brise_vue", "persistant"],
    resume: "Soleil · majestueux",
    populaire: false,
    ordre: 6,
    actif: true,
    source: "catalogue",
  },
  {
    id: "chene-vert",
    nom: "Chêne vert",
    nom_latin: "Quercus ilex",
    famille: "arbres",
    type: "arbre",
    palette_type: "sujet",
    photo_url: null,
    exposition: "soleil",
    taille_adulte: "20 m",
    floraison: null,
    rusticite: "Zone 7-10",
    sol: "Sol sec à frais",
    tags_envie: ["persistant", "brise_vue"],
    resume: "Soleil · méditerranéen",
    populaire: false,
    ordre: 7,
    actif: true,
    source: "catalogue",
  },
  {
    id: "erable-japon",
    nom: "Érable du Japon",
    nom_latin: "Acer palmatum",
    famille: "arbres",
    type: "arbre",
    palette_type: "sujet",
    photo_url: null,
    exposition: "mi-ombre",
    taille_adulte: "4 m",
    floraison: null,
    rusticite: "Zone 5-8",
    sol: "Terre légère, acide",
    tags_envie: ["ombre"],
    resume: "Mi-ombre · feuillage rouge",
    populaire: false,
    ordre: 8,
    actif: true,
    source: "catalogue",
  },
  {
    id: "geranium-rozanne",
    nom: "Géranium Rozanne",
    nom_latin: "Geranium × cantabrigiense",
    famille: "fleurs",
    type: "fleur",
    palette_type: null,
    photo_url: null,
    exposition: "soleil",
    taille_adulte: "50 cm",
    floraison: "Mai à octobre · bleu-violet",
    rusticite: "Zone 5-8",
    sol: "Tout sol ordinaire",
    tags_envie: ["floraison_violette", "sans_entretien"],
    resume: "Soleil · couvre-sol fleuri",
    populaire: false,
    ordre: 9,
    actif: true,
    source: "catalogue",
  },
  {
    id: "aster-novae-angliae",
    nom: "Aster",
    nom_latin: "Symphyotrichum novae-angliae",
    famille: "fleurs",
    type: "fleur",
    palette_type: null,
    photo_url: null,
    exposition: "soleil",
    taille_adulte: "1 m",
    floraison: "Automne · violet",
    rusticite: "Zone 4-8",
    sol: "Terre ordinaire",
    tags_envie: ["floraison_violette"],
    resume: "Soleil · fin de saison",
    populaire: false,
    ordre: 10,
    actif: true,
    source: "catalogue",
  },
  {
    id: "rose-new-dawn",
    nom: "Rose New Dawn",
    nom_latin: "Rosa New Dawn",
    famille: "rosiers",
    type: "fleur",
    palette_type: null,
    photo_url: null,
    exposition: "soleil",
    taille_adulte: "3 m",
    floraison: "Juin à octobre · rose pâle",
    rusticite: "Zone 6-9",
    sol: "Terre riche, profonde",
    tags_envie: ["persistant"],
    resume: "Soleil · grimpante parfumée",
    populaire: false,
    ordre: 11,
    actif: true,
    source: "catalogue",
  },
  {
    id: "rosier-rugosa",
    nom: "Rosier rugosa",
    nom_latin: "Rosa rugosa",
    famille: "rosiers",
    type: "plante",
    palette_type: null,
    photo_url: null,
    exposition: "soleil",
    taille_adulte: "1,5 m",
    floraison: "Été · rose ou blanc",
    rusticite: "Zone 3-8",
    sol: "Tout sol, même pauvre",
    tags_envie: ["persistant", "sans_entretien", "brise_vue"],
    resume: "Soleil · rustique · bord de mer",
    populaire: false,
    ordre: 12,
    actif: true,
    source: "catalogue",
  },
  {
    id: "buddleia",
    nom: "Buddleia",
    nom_latin: "Buddleja davidii",
    famille: "arbustes",
    type: "plante",
    palette_type: null,
    photo_url: null,
    exposition: "soleil",
    taille_adulte: "2,5 m",
    floraison: "Été · violet",
    rusticite: "Zone 5-9",
    sol: "Sol ordinaire",
    tags_envie: ["floraison_violette", "sans_entretien"],
    resume: "Soleil · papillons",
    populaire: false,
    ordre: 13,
    actif: true,
    source: "catalogue",
  },
  {
    id: "pittosporum",
    nom: "Pittosporum",
    nom_latin: "Pittosporum tenuifolium",
    famille: "arbustes",
    type: "plante",
    palette_type: null,
    photo_url: null,
    exposition: "mi-ombre",
    taille_adulte: "3 m",
    floraison: "Printemps · discret",
    rusticite: "Zone 8-10",
    sol: "Tout sol drainant",
    tags_envie: ["persistant", "brise_vue"],
    resume: "Mi-ombre · haie persistante",
    populaire: false,
    ordre: 14,
    actif: true,
    source: "catalogue",
  },
  {
    id: "heuchere",
    nom: "Heuchère",
    nom_latin: "Heuchera micrantha",
    famille: "vivaces",
    type: "plante",
    palette_type: null,
    photo_url: null,
    exposition: "mi-ombre",
    taille_adulte: "40 cm",
    floraison: "Été · rose",
    rusticite: "Zone 4-9",
    sol: "Terre humifère",
    tags_envie: ["ombre", "persistant"],
    resume: "Mi-ombre · feuillage coloré",
    populaire: false,
    ordre: 15,
    actif: true,
    source: "catalogue",
  },
];

export function getActiveCataloguePlants() {
  return CATALOGUE_PLANTS.filter((p) => p.actif !== false).sort((a, b) => a.ordre - b.ordre);
}

export function countByFamille(plants = getActiveCataloguePlants()) {
  const counts = Object.fromEntries(CATALOGUE_FAMILLES.map((f) => [f, 0]));
  for (const plant of plants) {
    if (counts[plant.famille] != null) counts[plant.famille] += 1;
  }
  return counts;
}

export function filterCataloguePlants({
  plants = getActiveCataloguePlants(),
  envieTag = null,
  famille = null,
  populaireOnly = false,
} = {}) {
  let list = plants;

  if (populaireOnly) {
    list = list.filter((p) => p.populaire);
  }
  if (envieTag) {
    list = list.filter((p) => p.tags_envie?.includes(envieTag));
  }
  if (famille) {
    list = list.filter((p) => p.famille === famille);
  }

  return list;
}
